---
title: "project2"
output: html_document
---

```{r setup, include=FALSE}
library(igraph)
library(ggplot2)
library(dplyr)
library(stringr)
```

```{r}
#read data and make it to a squre matrix
consolidated_df <- data.frame(matrix(ncol = 2, nrow = 0))
colnames(consolidated_df) <- c("Keyword1","Keyword2")
start_col <- 2  
end_col <- 13  
# Create consolidated dataframe with all keyword combinations that occur together
for(i in start_col:(end_col - 1)){
  for(j in (i+1):end_col)
  {
      temp <- df[,c(i,j)]
      colnames(temp) <- c("Keyword1","Keyword2")
      consolidated_df <- rbind(consolidated_df, temp)
  }
}
consolidated_df <- na.omit(consolidated_df)
edgelist <- data.frame(consolidated_df$Keyword1,consolidated_df$Keyword2)
my_edgelist<-graph.data.frame(edgelist)
my_adjacency_matrix<-get.adjacency(my_edgelist,sparse = FALSE, )
my_adjacency_matrix
```


```{r}
net1<-graph_from_adjacency_matrix(adj_matrix,mode="undirected", weighted = TRUE)
net1
plot.igraph(net1)
```
```{r}
# Compute node degree and strength
node_deg<-data.frame(degree(net1))
node_str<-data.frame(strength(net1))
```
```{r}
#Top 10 nodes by degree
node_deg_top10 <- node_deg%>%
 arrange(desc(degree.net1.))%>%
  top_n(10)
#Top 10 nodes by strenth
node_str_top10 <- node_str%>%
 arrange(desc(strength.net1.))%>%
  top_n(10)
```
```{r}
#Top 10 node pairs by weight
node_pairs_top10<-get.data.frame(net1)%>%
  arrange(desc(weight))%>%
  top_n(10)
node_pairs_top10<-head(node_pairs_top10,10)
```
```{r}
#Plot average strength on y-axis and degree on x-axis
deg_strength <- data.frame(cbind(node_deg, node_str))
deg_strength2 <- deg_strength %>% 
  arrange(degree.net1.)
avg_strength_deg <- deg_strength %>%
        group_by(degree.net1.) %>%
        summarise(avg_strength = mean(strength.net1.))
avg_strength_deg
# plot average strength vs degree
plot(avg_strength_deg$degree.net1.,avg_strength_deg$avg_strength,xlab="degree",ylab="average_strenth",pch=3)

```

