---
title: "HW3"
output: html_document
---
```{r}
library(lattice)
```

```{r}
#problem 1
x <- c(3.79, 2.99, 2.45, 2.14, 3.36, 2.05, 3.14, 3.54, 2.77, 2.91, 3.10, 1.84, 
       2.52, 3.22, 2.67, 2.52,2.71 ,2.75, 3.57, 3.85, 2.89, 2.83, 3.13, 2.44, 
       2.10, 3.71, 2.37, 2.68, 3.51, 3.37)
#(a)
Mean <- mean(x)
SD <- sd(x)
print(Mean)
print(SD)
#(b)
Histogram <- histogram(x,breaks=10)
print(Histogram)
#(c)
S_and_L <-stem(x,scale=2)
print(S_and_L)
#(d)
Box_plot <- boxplot(x)
print(Box_plot)
```

```{r}
#problem 2
A <-factorial(9)
print(paste0(" constructor can place these houses on a street if 6 lots are on one side of the street and 3 lots are on the opposite side in ways of : ",A))
```
```{r}
#problem 3
ways <- (factorial(365)/factorial(365-60))
print(paste0("No two students will have the same birth date in a class of size 60 have ways of :",ways))
```

```{r}
#problem 4
#(a)
#P( tax-free bonds or mutual funds) = P(tax-free bonds) + P(mutual funds) - P(both)
P1<- 0.6+0.3-0.15
print(paste0("The probability of either tax-free bonds or mutual funds is:",P1))
#(b)
#P(neither tax-free bonds nor mutual funds)=1-P( tax-free bonds or mutual funds)
P2 <- 1-0.75
print(paste0("The probability of neither tax-free bonds nor mutual funds is:",P2))
```

```{r}
#problem 5
#(a)
#5 cards can be hold in the ways of : 52!/(5!*(52-5)!) = 2598960
#3 aces can be hold in ways of: 4!/(3!*1!) = 4
#number of ways holding the other 2 cards: 48!/(2!*46!)=1128
#The probability of holding 3 aces is 4/2598960  
w_5 <- factorial(52)/(factorial(5)*factorial(52-5))
w_3 <- factorial(4)/(factorial(3)*1)
w_2 <- factorial(48)/(factorial(2)*factorial(46))
P_3 <- (w_3*w_2)/w_5

#(b)
#4 hearts can be hold in the ways of :13!/4!*9! =715
#1 club can be hold in the ways of : 13!/1!*12! = 13
#The probability of holding 4 hearts and 1 club is (13*715)/2598960
w_h <- factorial(13)/(factorial(4)*factorial(9))
w_c <- factorial(13)/(factorial(1)*factorial(12))
P_h_c <- (w_h *w_c)/w_5
```

```{r}
#problem 6
#A vehicle entering the Luray Caverns has Canadian license plates is P(A) = 0.12
#A vehicle entering the Luray Caverns is a Camper is P(B) = 0.28
#A camper with Canadian license plates is P(A and B) = 0.09

#(a)
# The probability of a camper entering the Luray Caverns has Canadian license plates is P(A|B) = P(A and B)/ P(B) = 0.09/0.28 = 0.32143 
P1 <- 0.09/0.28

#(b)
#The probability of a vehicle with Canadian license plates entering the Luray Caverns is a camper is P(B|A) = P(A and B)/P(A) = 0.09/0.12 = 0.75
P2 <- 0.09/0.12

#(c)
# The probability of a vehicle entering the Luray Caverns does not have Canadian plates or is not a camper is : P(A'OR B') = 1- P(A and B) = 1-0.09 =0.91
P3 <- 1-0.09
```

```{r}
#problem7
P_L<-0.75
P_S<-1-0.75
P_RL<-0.6
P_RS<-0.3
P_LR<-(0.6*0.75)/(0.6*0.75+0.3*0.25)
print(paste0("The probabilty for a randomly selected buyer purchases a roller and a can of paint and the paint is latex is:",P_LR))
```

```{r}
#problem 8
# hand writted down







